# Generated by Django 2.0 on 2017-07-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0002_tuits_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tuits',
            new_name='TuitLocation',
        ),
    ]
