# Generated by Django 2.0 on 2017-07-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0003_auto_20170731_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitlocation',
            name='category',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
