# Generated by Django 2.0 on 2017-08-04 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0005_auto_20170731_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitlocation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
