# Generated by Django 2.0 on 2017-08-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0006_tuitlocation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitlocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tuitlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
