# Generated by Django 2.0 on 2017-08-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0007_auto_20170804_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
