# Generated by Django 2.0 on 2017-08-14 22:47

from django.db import migrations, models
import tuits.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0008_tuitlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[tuits.validators.validate_category]),
        ),
    ]
